max-distance-from-center: 64
day: 0
event-start-time: "12:00"
event-message-interval: 2000
messages:
  no-event-message: "Dzisiaj brak eventu. Eventy będą zaczynać się od 3. dnia."
  no-event-until-message: "Event rozpoczyna się o "
apocalypse:
  firework-interval: 10
  skeleton-interval: 160