name: microppplugin
version: '1.0-SNAPSHOT'
main: com.github.zabbum.microppplugin.Microppplugin
description: Plugin for microPP server
authors:
  - XmoxEL
api-version: '1.21'
loadbefore:
  - LuckPerms
depend:
  - LuckPerms

commands:
  eventmessage:
    description: "Display current event message"
    usage: "/eventmessage"
    permission: microppplugin.command.eventmessage
    permission-message: "Nope"
  getstick:
    description: "Get stick"
    usage: "/getstick"
    permission: microppplugin.command.getstick
    permission-message: "Nope"
  gethorse:
    description: "Get horse artifact"
    usage: "/gethorse"
    permission: microppplugin.command.gethorse
    permission-message: "Nope"
  apocalypse:
    description: "Apocalypse event"
    usage: "/apocalypse < start | end >"
    permission: microppplugin.command.apocalypse
    permission-message: "Nope"
  setborder:
    description: "Set world border"
    usage: "/setborder < size devided by 2 >"
    permission: microppplugin.command.setborder
    permission-message: "Nope"